#!/bin/bash
#
# upgrade paedML 3.0 to 4.0
# online wrapper script
#
# cmdline parameter: path to paedML/openML iso file
# downloads openML iso if no iso file is given on cmdline
# invokes at least upgrade script on cdrom
#
# 09.03.2009
# 
# Thomas Schmitt
# <schmitt@lmz-bw.de>
# GPL V3
#

. /usr/share/linuxmuster/config/dist.conf
. $HELPERFUNCTIONS

if [ "$(cat /etc/debian_version)" != "3.1" ]; then
	echo "Das Upgrade funktioniert nur mit Debian 3.1!"
	exit 0
fi

if ! grep -q "paedML Linux 3.0" /etc/issue; then
	echo "Das Upgrade funktioniert nur mit paedML Linux 3.0!"
	exit 0
fi

CURDIR=`pwd`

# check isofile given on cmdline
if [ -n "$1" ]; then
	CDNAME=$(basename $1)
	if [ "$CDNAME" = "$FREECDNAME" -o "$CDNAME" = "$NONFREECDNAME" ]; then
    echo "Verwende ISO-Datei $CDNAME."
		DLDIR=${1%\/$CDNAME}
	else
		echo "Unbekannte ISO-Datei: $CDNAME."
		exit 1
	fi
else
	# check free space for download dir
	for i in $CURDIR $ADMINSHOME/$ADMINISTRATOR /var/tmp; do
		if check_free_space $i 700000; then
			DLDIR=$i
			break
		fi
	done
	[ -z "$DLDIR" ] && exit 1
	# download iso file
	CDNAME=$FREECDNAME
	echo "Lade $CDNAME nach $DLDIR herunter."
	if ! wget $ISOURL/$CDNAME -O $DLDIR/$CDNAME; then
		echo "Download von $CDNAME fehlgeschlagen!"
		exit 1
	fi
fi

# ISODATEI unter /cdrom mounten
if ! mount -o loop,exec $DLDIR/$CDNAME /cdrom; then
	echo "Kann $DLDIR/$CDNAME nicht mounten!"
	exit 1
fi

/cdrom/paedml40-upgrade

if ! umount /cdrom; then
	echo "Fehler: Kann $CDNAME nicht aushaengen!"
fi

