#!/bin/bash
#
# upgrade paedML 4.0.x to 5.0.x
# online wrapper script
#
# cmdline parameter: path to paedML/openML iso file
# downloads openML iso if no iso file is given on cmdline
# invokes at least upgrade script on cdrom
#
# 2010-05-20
# 
# Thomas Schmitt
# <schmitt@lmz-bw.de>
# GPL V3
#

. /usr/share/linuxmuster/config/dist.conf
. $HELPERFUNCTIONS

if [ "$(cat /etc/debian_version)" != "4.0" ]; then
	echo "Das Upgrade funktioniert nur mit Debian 3.1!"
	exit 0
fi

if ! grep -q "[op][pa][e][nd]ML Linux 4\.0\.[4-5]" /etc/issue; then
	echo "Das Upgrade funktioniert nur mit openML/paedML Linux 4.0.4/4.0.5!"
	exit 0
fi

if ! check_free_space /var 1000000; then
 echo "Zuwenig Speicherplatz unter /var. Stellen Sie sicher, dass dort 1GB freier Platz zur Verfügung steht."
 exit 1
fi

. $DATADIR/upgrade/paedml50-upgrade.sh 2>&1 | tee -a /var/log/linuxmuster/paedml50-upgrade.log

