#!/bin/sh
#
# dist-upgrade from paedML Linux 3.0 to Etch
#
# Thomas Schmitt <schmitt@lmz-bw.de>
# 23.04.2008
# GPL V2
#

. /usr/share/linuxmuster/config/dist.conf
. $HELPERFUNCTIONS

if [ "$(cat /etc/debian_version)" = "4.0" -a "$1" != "--force" ]; then
	echo "Das System wurde bereits auf Debian 4.0 aktualisiert!"
	exit 0
fi

LOGFILE=$LOGDIR/etch-ugrade.log

. /usr/share/linuxmuster/upgrade/etch-upgrade.sh | tee -a $LOGFILE

