#!/bin/bash
#
# upgrade paedML 4.0.x to 5.1.x
# online wrapper script
#
# cmdline parameter: path to paedML/openML iso file
# downloads openML iso if no iso file is given on cmdline
# invokes at least upgrade script
#
# $Id$
# 
# Thomas Schmitt
# <schmitt@lmz-bw.de>
# GPL V3
#

. /usr/share/linuxmuster/config/dist.conf
. $HELPERFUNCTIONS
# logging
LOGFILE="$LOGDIR/paedml51-upgrade.log"
exec > >(tee -a $LOGFILE)

NOW=`date`

# print help
usage(){
 echo "Usage: `basename $0` <options>"
 echo
 echo "Options:"
 echo
 echo " -c                   Upgrade with real paedML/openML-CDROM placed in the"
 echo "                      local drive."
 echo " -d                   Download and upgrade with openML ISO. This is the default."
 echo " -f                   Force upgrade without version test."
 echo " -i <path to isofile> Use this local isofile to upgrade."
 echo " -h                   Show this help."
 echo
 echo "Note: -c, -d and -i exclude each other and will not be evalutated if"
 echo "running directly from cdrom."
 echo
 exit 1
}


# downloading openML/paedML iso
download(){
 DLDIR=$ADMINSHOME/$ADMINISTRATOR/iso
 mkdir -p $DLDIR
 if [ ! -s "$DLDIR/$FREECDNAME" -a ! -s "$DLDIR/${FREECDNAME}.md5" ]; then
  echo "Lade $FREECDNAME herunter ..."
  rm -f $DLDIR/${FREECDNAME}*
  wget $ISOURL/$FREECDNAME -O $DLDIR/$FREECDNAME
  wget $ISOURL/${FREECDNAME}.md5 -O $DLDIR/${FREECDNAME}.md5
  chown $ADMINISTRATOR $DLDIR -R
 else
  echo "Überspringe Download. $FREECDNAME ist bereits in $DLDIR vorhanden."
 fi
 cd $DLDIR
 echo "Überpruefe MD5-Summe der IS0-Datei ..."
 md5sum -c ${FREECDNAME}.md5 || exit 1
 cd ~
 # mount iso
 if ! mount -o loop "$DLDIR/$FREECDNAME" "$CDROOT"; then
  echo "Kann $FREECDNAME nicht einhängen!"
  exit 1
 fi
 checked=yes
}


echo
echo "####"
echo "#### paedML/openML Linux Distributions-Upgrade auf Debian 5.0.3 Lenny"
echo "#### Startzeit: $NOW"
echo "####"
echo


# check for firewall type
fwtype="$(debconf-show linuxmuster-base | grep fwconfig | awk -F \: '{ print $2}' | awk '{ print $1}')"
if [ "$fwtype" = "integrated" ]; then
 echo "Integrierte Firewall erkannt."
 echo "Ab Version 5.1.0 wird die integrierte Firewall nicht mehr unterstützt."
 echo "Stellen Sie auf dedizierte Firewall um und starten Sie das Upgrade danach erneut."
 exit 1
fi


# check if apt-ftparchive is present
APTARCHIVE="$(which apt-ftparchive)"
if [ -z "$APTARCHIVE" ]; then
 echo "Installiere apt-utils."
 aptitude -y install apt-utils
fi
APTARCHIVE="$(which apt-ftparchive)"
if [ -z "$APTARCHIVE" ]; then
 echo "apt-ftparchive nicht gefunden!"
 exit 1
fi


# check if we are running from cdrom
[ "$(basename "$0")" = "paedml51-cdrom-upgrade" ] && CDROOT="$(dirname "$0")"


# parse commandline arguments if not running from cdrom
while getopts ":cdfhi:" opt; do
 case $opt in
  c) CDROM=yes ;;
  d) DOWNLOAD=yes ;;
  f) FORCE=yes ;;
  i) ISOFILE="$OPTARG" ;;
  h) usage ;;
  \?) echo "Invalid option: -$OPTARG" >&2
      usage ;;
  :) echo "Option -$OPTARG requires an argument." >&2
     usage ;;
 esac
done

# check args
if [ -z "$CDROOT" ]; then
 
 [ -n "$CDROM" -a -n "$ISOFILE" -a -n "$DOWNLOAD" ] && usage
 [ -n "$CDROM" -a -n "$DOWNLOAD" ] && usage
 [ -n "$ISOFILE" -a -n "$DOWNLOAD" ] && usage
 [ -n "$CDROM" -a -n "$ISOFILE" ] && usage
 [ -z "$CDROM" -a -z "$ISOFILE" -a -z "$DOWNLOAD" ] && DOWNLOAD=yes
 if [ -n "$ISOFILE" -a ! -s "$ISOFILE" ]; then
  echo "$ISOFILE does not exist!"
  usage
 fi

 CDROOT=/cdrom
 mount | grep -q "$CDROOT" && umount "$CDROOT" 2>&1 >> $LOGFILE

 if [ -n "$CDROM" ]; then
  mount "$CDROOT" || exit 1
 elif [ -s "$ISOFILE" ]; then
  mount -o loop "$ISOFILE" "$CDROOT" || exit 1
 else
  download
 fi

fi


# check for nfs mounts
if mount | awk '{ print $5 }' | grep -qw nfs; then
 echo
 echo "Ein NFS-Share ist eingehängt! Bitte aushängen und nochmal starten!"
 exit 1
fi


# skip version test
if [ -n "$FORCE" ]; then

 echo "-f angegeben: überspringe Versionsprüfung!"
 echo

else

 if [ "$(cat /etc/debian_version)" != "4.0" ]; then
  echo "Das Upgrade lässt sich nur mit Debian 4.0 durchführen!"
  exit 0
 fi

 if ! grep -q "[op][pa][e][nd]ML Linux 4\.0\.6" /etc/issue; then
  echo "Das Upgrade lässt sich nur mit openML/paedML Linux 4.0.6 durchführen!"
  exit 0
 fi

fi # force


# put apt in unattended mode
tweak_apt() {
 export DEBIAN_FRONTEND=noninteractive
 export DEBIAN_PRIORITY=critical
 export DEBCONF_TERSE=yes
 export DEBCONF_NOWARNINGS=yes
 echo 'DPkg::Options {"--force-configure-any";"--force-confmiss";"--force-confold";"--force-confdef";"--force-bad-verify";"--force-overwrite";};' > /etc/apt/apt.conf.d/99upgrade
 echo 'aptitude::CmdLine::Ignore-Trust-Violations "true";' >> /etc/apt/apt.conf.d/99upgrade
 echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/99upgrade
 echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/99upgrade
 dpkg -l linuxmuster-base | grep -q ^ii &> /dev/null || aptitude -y install linuxmuster-base
}


# check medium if it was not already checked
if [ -z "$checked" ]; then
 echo "Prüfe Upgrade-Medium."
 cd "$CDROOT"
 RC=0
 if ! grep -q "ML Linux 5.1" .disk/info; then
  echo "Das ist keine paedML/openML-CDROM der Version 5.1.x!"
  RC=1
 fi
 if [ "$RC" = "0" ]; then
  if ! md5sum -c md5sum.txt; then
   echo "Prüfsummenfehler!"
   RC=1
  fi
 fi
 if [ "$RC" != "0" ]; then
  cd ~
  umount "$CDROOT" 2>> $LOGFILE 1>> $LOGFILE
  eject "$CDROOT" 2>> $LOGFILE 1>> $LOGFILE
  exit 1
 fi
fi


# check if newer linuxmuster-base package is on cdrom and install it
cd "$CDROOT/pool/main/l/linuxmuster" || exit 1
curver="$(dpkg -s linuxmuster-base | grep ^Version | awk '{ print $2 }')"
cdpkg="$(ls linuxmuster-base_*.deb | tail -1)"
if [ -z "$cdpkg" ]; then
 echo "Fehler! Kein linuxmuster-base-Paket gefunden!"
 cd ~
 umount "$CDROOT" 2>> $LOGFILE 1>> $LOGFILE
 eject "$CDROOT" 2>> $LOGFILE 1>> $LOGFILE
 exit 1
fi
cdver="$(echo "$cdpkg" | awk -F \_ '{ print $2 }')"
if [ "$cdver" \> "$curver" ]; then
 echo "Aktualisiere linuxmuster-base: $curver -> $cdver."
 dpkg --force-all -i "$cdpkg"
 # reread paedml environment
 . /usr/share/linuxmuster/config/dist.conf
 . $HELPERFUNCTIONS
fi
cd ~


# check for enough space on /var
if ! check_free_space /var 1500000; then
 echo "Zuwenig Speicherplatz unter /var. Stellen Sie sicher, dass dort mind. 1,5GB freier Platz zur Verfügung steht."
 exit 1
fi


# copy packages from cdrom to cache and create local repo
find "$CDROOT/pool" -name \*.deb -exec cp -v '{}' /var/cache/apt/archives \;
echo "Erstelle lokales Paket-Repository ..."
cd /var/cache/apt/archives
"$APTARCHIVE" packages ./ > Packages
if [ ! -s Packages ]; then
 echo " fehlgeschlagen!"
 exit 1
fi


# source upgradeskript from /tmp
cd ~
cp $DATADIR/upgrade/paedml51-upgrade.sh /tmp || exit 1
. /tmp/paedml51-upgrade.sh 2>&1


# umount and eject cdrom if possible
umount "$CDROOT" 2>> $LOGFILE 1>> $LOGFILE
eject "$CDROOT" 2>> $LOGFILE 1>> $LOGFILE


echo
echo "####"
echo "#### Beendet um `date`."
echo "#### Starten Sie den Server neu!"
echo "####"
echo

