#!/bin/bash
# postinst script for linuxmuster
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package
#

# Source debconf library.
. /usr/share/debconf/confmodule

db_version 2.0

releasenr=RC4
releasename="paedML Linux 4.0.0"
codename=Griffelschbitzer
oldissue="paedML Linux 3.0"

# check if all templates present
for i in linuxmuster-base/intro linuxmuster-base/country linuxmuster-base/state \
         linuxmuster-base/location linuxmuster-base/schoolname shared/organization \
         linuxmuster-base/servername linuxmuster-base/domainname linuxmuster-base/workgroup \
         linuxmuster-base/fwconfig linuxmuster-base/externtype linuxmuster-base/externip \
         linuxmuster-base/externmask linuxmuster-base/gatewayip linuxmuster-base/dnsforwarders \
         linuxmuster-base/dsluser linuxmuster-base/dslpasswd linuxmuster-base/smtprelay \
         linuxmuster-base/rootpw linuxmuster-base/rootpw_confirm linuxmuster-base/adminpw \
         linuxmuster-base/adminpw_confirm linuxmuster-base/pgmadminpw linuxmuster-base/pgmadminpw_confirm \
         linuxmuster-base/wwwadminpw linuxmuster-base/wwwadminpw_confirm linuxmuster-base/ipcoppw \
         linuxmuster-base/ipcoppw_confirm linuxmuster-base/sambasid linuxmuster-base/internmask \
         linuxmuster-base/internmask_short linuxmuster-base/internsubrange linuxmuster-base/nicmenu \
         linuxmuster-base/ifmenu linuxmuster-base/mac_extern linuxmuster-base/mac_intern \
         linuxmuster-base/mac_wlan linuxmuster-base/mac_dmz linuxmuster-base/imaging \
         shared/present-sun-dlj-v1-1 shared/accepted-sun-dlj-v1-1; do

	if ! db_get linuxmuster-base/$i; then
		db_set linuxmuster-base/$i "" || true
		db_go
	fi

done

case "$1" in
    configure)

      # read linuxmuster defaults
      . /usr/share/linuxmuster/config/dist.conf

      # make configs executable so that perl scripts can source it
      chmod 755 /usr/share/linuxmuster/config/dist.conf
      chmod 755 /etc/linuxmuster/backup.conf
      [ -e /etc/default/linuxmuster-base ] && chmod 755 /etc/default/linuxmuster-base

      # only root may use helperfunctions.sh
      chmod 600 $HELPERFUNCTIONS

      # check all necessary dirs and links and create them if needed
      for i in $NETLOGONDIR $PROGSDIR $CDSDIR $BACKUPDIR $BACKUPMNTPOINT \
               $LOGINCACHE $LOGDIR; do

        [ -d "$i" ] || mkdir -p $i

      done

      # add startup scripts to runlevels
      update-rc.d linuxmuster-base defaults
      update-rc.d linuxmuster-nic-setup start 40 S .

      # create and correct dirs and files
      [ -d /etc/skel/windows ] && rm -rf /etc/skel/windows
      [ -d /etc/skel/cups-pdf ] && rm -rf /etc/skel/cups-pdf
      [ -d /var/lib/rembo/files/global ] || mkdir -p /var/lib/rembo/files/global
      [ -e /var/lib/rembo/files/global/wimport_data ] || touch /var/lib/rembo/files/global/wimport_data
      [ -e /etc/linuxmuster/workstations ] || touch /etc/linuxmuster/workstations
      [ -e "$BLOCKEDHOSTSINTERNET" ] || touch $BLOCKEDHOSTSINTERNET
      [ -e "$BLOCKEDHOSTSINTRANET" ] || touch $BLOCKEDHOSTSINTRANET
      [ -e "$UNFILTEREDHOSTS" ] || touch $UNFILTEREDHOSTS

      # dummy dhcpd.conf
      if [ ! -f "$DHCPDCONF" ]; then
        [ -d "${DHCPDCONF%/*}" ] || mkdir -p ${DHCPDCONF%/*}
        touch $DHCPDCONF
      fi

      # system groups and users which are needed by udevd
      for i in fuse kvm nvram rdma scanner tss; do
        if ! grep -q ^${i}: /etc/group; then
          addgroup --system $i
        fi
      done
      if ! grep -q ^tss: /etc/passwd; then
        adduser --system --no-create-home --ingroup tss --disabled-login tss
      fi

      # check debian_version
      if [ "$(cat /etc/debian_version)" != "4.0" ]; then
        echo "This is not Debian 4.0 Etch. Please upgrade your system!"
        exit 0
      fi

      # upgrade tasks
      if [ -e "$INSTALLED" ]; then

        if ! . $HELPERFUNCTIONS; then
          echo "Cannot read $HELPERFUNCTIONS!"
          exit 1
        fi

        # check if smtprelay is in $NETWORKSETTINGS
        if ! grep -q smtprelay $NETWORKSETTINGS; then
          db_get linuxmuster/base smtprelay || true
          smtprelay=$RET
          smtprelay=${smtprelay#[0-9] }
          echo "smtprelay=\"$smtprelay\"" >> $NETWORKSETTINGS
        fi

        # messages for config file headers
        message1="##### Do not change this file! It will be overwritten!"
	message2="##### This configuration file was automatically created by linuxmuster-base!"
	message3="##### Last Modification: `date`"

        # some variables we need for patching
        # added imaging (1.2-6)
        servername=`hostname -s`
        domainname=`dnsdomainname`
        db_get linuxmuster-base/country || true
        country=$RET
        db_get linuxmuster-base/state || true
        state=$RET
        db_get linuxmuster-base/location || true
        location=$RET
        db_get linuxmuster-base/schoolname || true
        schoolname=$RET
        db_get linuxmuster-base/workgroup || true
        workgroup=$RET
        workgroup=${workgroup#[0-9] }
        internsub=`echo $serverip | awk -F. '{ print $2 }'`
	serverrev_short=1.1.$internsub
	ipcoprev_short=254.1.$internsub

        # patch samba
        sed -e "s/@@message1@@/${message1}/g
                s/@@message2@@/${message2}/g
                s/@@message3@@/${message3}/g
                s/@@serverip@@/${serverip}/g
                s/@@internmask@@/${internmask}/g
                s/@@workgroup@@/${workgroup}/g
                s/@@domadmin@@/${DOMADMIN}/g
                s/@@administrator@@/${ADMINISTRATOR}/g
                s/@@domadmins@@/${DOMADMINS}/g
                s/@@teachersgroup@@/${TEACHERSGROUP}/g
                s/@@basedn@@/${basedn}/g" $SMBCONFTEMPLATE.$imaging > /etc/samba/smb.conf

	# samba reload only if postgres and/or samba are running
	if ps ax | grep slapd | grep -v grep &> /dev/null; then
		if ps ax | grep smbd | grep -v grep &> /dev/null; then
			/etc/init.d/samba reload
	        	# restore samba ldap admin password
        		smbpasswd -w `cat /etc/ldap.secret`
		else
			echo "Samba is not running! Skipping samba reload!"
			echo "You have to restart samba after package update!"
		fi
	else
		echo "The LDAP daemon (slapd) is not running! Skipping samba reload!"
		echo "You have to reload samba after package update!"
	fi

        # apache2 adding port 242 for schulkonsole
        apache_ports=/etc/apache2/ports.conf
        if ! grep -q 242 $apache_ports; then
          cp -f $STATICTPLDIR$apache_ports $apache_ports
        fi

	# removing schulkonsole's obsolete apache2 configuration
	if [ -L /etc/apache2/conf.d/schulkonsole ]; then
		rm /etc/apache2/conf.d/schulkonsole
        fi

	# create new certificate skript and create new certificate
	if [ ! -e "$SCRIPTSDIR/create-ssl-cert.sh" ]; then
		echo "Creating new server certificate ..."
		sed -e "s/@@country@@/${country}/
			s/@@state@@/${state}/
			s/@@location@@/${location}/
			s/@@schoolname@@/${schoolname}/
			s/@@servername@@/${servername}/
			s/@@domainname@@/${domainname}/g
			s/@@administrator@@/${ADMINISTRATOR}/" $DYNTPLDIR/01_certificates/create-ssl-cert.sh > $SCRIPTSDIR/create-ssl-cert.sh
		chmod 744 $SCRIPTSDIR/create-ssl-cert.sh
		$SCRIPTSDIR/create-ssl-cert.sh
	fi

        # fixing pam configuration
        if grep ^account /etc/pam.d/login | grep -q pam_access.so; then
  	  echo "pam configuration is up to date. :-)"
        else
          echo "Updating pam configuration ..."
          cp -f $STATICTPLDIR/etc/pam.d/* /etc/pam.d
          cp -f $STATICTPLDIR/etc/nsswitch.conf /etc
          sed -e "s/@@administrator@@/$ADMINISTRATOR/" $DYNTPLDIR/17_admins/access.conf > /etc/security/access.conf
	  echo "ATTENTION!"
	  echo "Only root and $ADMINISTRATOR are allowed to login on the server!"
	  echo "To change this behaviour you have to edit /etc/security/access.conf!"
        fi

        # update cron scripts
        # ntpdate
        if [ -e /etc/cron.hourly/ntpdate ]; then
          echo "Removing ntpdate cron script ..."
          rm /etc/cron.hourly/ntpdate
        fi

        # bind9
        # permissions
        chown root:bind /etc/bind
        chmod 775 /etc/bind
        chown root:bind /etc/bind/db.10
        chown root:bind /etc/bind/db.linuxmuster
        chmod 664 /etc/bind/db.10
        chmod 664 /etc/bind/db.linuxmuster


        # apt
#        [ -e /etc/apt/apt.conf ] && cp /etc/apt/apt.conf /etc/apt/apt.conf.dpkg-old
#        echo "Updating /etc/apt/apt.conf ..."
#        cp -f $STATICTPLDIR/etc/apt/apt.conf /etc/apt
	# checking for correct sources.list
	if grep -q lml40-updates /etc/apt/sources.list; then
		backup_file /etc/apt/sources.list
		echo "Updating sources.list ..."
		sed -e 's/lml40-updates/paedml40-updates/' -i /etc/apt/sources.list
	fi
#	while read line; do
#		[ "${line:0:3}" != "deb" ] && continue
#		if ! grep -q "$line" /etc/apt/sources.list; then
#			[ -z "$slist_changed" ] && gzip -c /etc/apt/sources.list > $BACKUPDIR/sources.list-$DATETIME.gz
#			echo "Adding $line to /etc/apt/sources.list ..."
#			echo "$line" >> /etc/apt/sources.list
#			slist_changed=yes
#		fi
#	done <$STATICTPLDIR/etc/apt/sources.list.online

        # environment
        if [ ! -e /etc/environment ]; then
          echo "Updating /etc/environment ..."
          cp -f $STATICTPLDIR/etc/environment /etc
          cp -f $STATICTPLDIR/etc/profile /etc
        fi
	if ! grep -q "export LANG" /etc/profile; then
		backup_file /etc/profile
		sed -e "/^export PATH/a\
export LANG" -i /etc/profile
	fi

        # shadow passwords
        if [ ! -e /etc/shadow ]; then
          shadowconfig on
        fi

        # remove false link to backup mountpoint
	[ -L /_backup ] && rm /_backup

        # openldap permissions
        chown root:root /etc/ldap/ldap.conf
        chmod 644 /etc/ldap/ldap.conf
        chown root:root /etc/ldap/slapd.conf
        chmod 600 /etc/ldap/slapd.conf
        chown root:root /etc/odbc.ini
        chmod 644  /etc/odbc.ini
        chmod 600 /etc/ldap/slapd.conf*

        # bug #123, adding ipcop handling to /etc/init.d/networking
        if ! grep -q ^doipcop /etc/init.d/networking; then
          echo "Updating /etc/init.d/networking (Bug #123) ..."
          cp /etc/init.d/networking /etc/init.d/networking.dpkg-dist
          cp $STATICTPLDIR/etc/init.d/networking /etc/init.d
        fi
	# fixing typo in /etc/init.d/networking
        if grep -q dopicop /etc/init.d/networking; then
          echo "Fixing typo in /etc/init.d/networking ..."
          cp $STATICTPLDIR/etc/init.d/networking /etc/init.d
        fi
	[ -e /etc/init.d/networking.dpkg-dist ] && chmod 644 /etc/init.d/networking.dpkg-dist

	# remove old nameif script and installing new linuxmuster-nic-setup
	if [ -e /etc/init.d/nameif ]; then
		echo "Fixing mac address handling (Bug #86) ..."
		#  first save the mac assignments
		mac_extern=`grep "^nameif extern" /etc/init.d/nameif | cut -f3 -d" "`
		if [ -n "$mac_extern" ]; then
			toupper $mac_extern
			mac_extern=$RET
			db_set linuxmuster-base/mac_extern $mac_extern || true
		fi
		mac_intern=`grep "^nameif intern" /etc/init.d/nameif | cut -f3 -d" "`
		if [ -n "$mac_intern" ]; then
			toupper $mac_intern
			mac_intern=$RET
			db_set linuxmuster-base/mac_intern $mac_intern || true
		fi
		mac_wlan=`grep "^nameif wlan" /etc/init.d/nameif | cut -f3 -d" "`
		if [ -n "$mac_wlan" ]; then
			toupper $mac_wlan
			mac_wlan=$RET
			db_set linuxmuster-base/mac_wlan $mac_wlan || true
		fi
		mac_dmz=`grep "^nameif dmz" /etc/init.d/nameif | cut -f3 -d" "`
		if [ -n "$mac_dmz" ]; then
			toupper $mac_dmz
			mac_dmz=$RET
			db_set linuxmuster-base/mac_dmz $mac_dmz || true
		fi
		# write them to network.settings
		grep -v ^mac_ $NETWORKSETTINGS > $NETWORKSETTINGS.tmp
		mv $NETWORKSETTINGS.tmp $NETWORKSETTINGS
		echo "mac_extern=$mac_extern" >> $NETWORKSETTINGS
		echo "mac_intern=$mac_intern" >> $NETWORKSETTINGS
		echo "mac_wlan=$mac_wlan" >> $NETWORKSETTINGS
		echo "mac_dmz=$mac_dmz" >> $NETWORKSETTINGS
		update-rc.d -f nameif remove
		mv /etc/init.d/nameif /etc/init.d/nameif.dpkg-old
		chmod 644 /etc/init.d/nameif.dpkg-old

	fi

	# restoring PDF-Printer
#	if [ ! -f /etc/cups/ppd/PDF-Printer.ppd ]; then
#		echo "Restoring PDF-Printer driver ..."
#		cp $STATICTPLDIR/etc/cups/ppd/PDF-Printer.ppd /etc/cups/ppd
#		cups_restart=yes
#	fi
	# restoring PDF-Printer definition
#	if ! grep -q PDF-Printer /etc/cups/printers.conf; then
#		echo "Restoring PDF-Printer definition ..."
#		cp /etc/cups/printers.conf /etc/cups/printers.conf.dpkg-old
#		cat $STATICTPLDIR/etc/cups/printers.conf | grep -v ^# >> /etc/cups/printers.conf
#		cups_restart=yes
#	fi
	# upgrading cups-pdf printer driver
#	if [ -f /usr/share/ppd/cups-pdf/PostscriptColor.ppd ]; then
#		if ! diff -q /usr/share/ppd/cups-pdf/PostscriptColor.ppd /etc/cups/ppd/PDF-Printer.ppd &> /dev/null; then
#			echo "Upgrading cups-pdf printer driver ..."
#			cp /usr/share/ppd/cups-pdf/PostscriptColor.ppd /etc/cups/ppd/PDF-Printer.ppd
#			cups_restart=yes
#		fi
#	fi
	# fixing cupsys init start nr
	if [ -e /etc/rc2.d/S20cupsys ]; then
		echo "Fixing cupsys' init start nr ..."
		update-rc.d -f cupsys remove
		update-rc.d cupsys start 21 2 3 4 5 . stop 19 0 1 6 .
		cups_restart=yes
	fi
	if [ -n "$cups_restart" ]; then
			/etc/init.d/cupsys force-reload || true
	fi

	# extraschueler.txt, extrakurse.txt
	for i in extraschueler.txt extrakurse.txt entfernen.txt sperrklassen.txt; do
		[ -e "/etc/sophomorix/user/$i" ] || cp $STATICTPLDIR/etc/sophomorix/user/$i /etc/sophomorix/user
	done

        # removing old cyrus21 runlevel links
	if [ -e /etc/rc2.d/S20cyrus2.2 ]; then
		if [ -e /etc/rc2.d/S20cyrus21 ]; then
			update-rc.d -f cyrus21 remove
		fi
	fi

	# updating schulkonsole's db.conf
	if grep -q ^"Username=ldap" /etc/linuxmuster/schulkonsole/db.conf; then
		echo "Updating database configuration for linuxmuster-schulkonsole ..."
		cp $STATICTPLDIR/etc/linuxmuster/schulkonsole/db.conf /etc/linuxmuster/schulkonsole/db.conf.obsolete
		cp $STATICTPLDIR/etc/linuxmuster/schulkonsole/db.conf /etc/linuxmuster/schulkonsole
		chown www-data:www-data /etc/linuxmuster/schulkonsole/db.conf*
		chmod 600 /etc/linuxmuster/schulkonsole/db.conf*
	fi

	# repair admin accounts and groupmappings
	$SCRIPTSDIR/repair-admins.sh

	# provide paedML index.html
	indexhtml=/var/www/apache2-default/index.html
	template=${indexhtml}.tpl
	if [ -e "$template" ]; then
		if ! grep -q "$servername.$domainname" $indexhtml; then
			[ -e "$indexhtml" ] && mv $indexhtml ${indexhtml}.dpkg-old
			sed -e "s/@@servername@@/$servername/g
			        s/@@domainname@@/$domainname/g" $template > $indexhtml
		fi
		# update version
		if grep -q "$oldissue" $indexhtml; then
			mv $indexhtml ${indexhtml}.dpkg-old
			sed -e "s/$oldissue/$releasename/g" $template > $indexhtml
		fi
	fi

	# updating release information
	if ! grep -q "$releasenr" /etc/issue; then
		buildnr=`cat /etc/issue | cut -f9 -d" "`
		echo "$releasename / Release $releasenr / Build $buildnr / Codename $codename" > /etc/issue
		cp /etc/issue /etc/issue.net
		cat /etc/issue
	fi

	# removing passwd3 files (1.1-7)
	[ -e /etc/horde/passwd3 ] && rm -rf /etc/horde/passwd3
	[ -e /usr/share/horde3/passwd ] && rm -rf /usr/share/horde3/passwd
	[ -e /usr/share/doc/passwd3 ] && rm -rf /usr/share/doc/passwd3

        # restoring internal firewall
        . /etc/default/linuxmuster-base
        if [ "$START_LINUXMUSTER" = "yes" ]; then
          if ! iptables -L | grep -q "$FIREWALLTEST"; then
            /etc/init.d/linuxmuster-base start
          fi
        fi

	# adding imaging variable (1.2-14)
	if ! grep -q ^imaging $NETWORKSETTINGS; then
		if [ -z "$imaging" ]; then
			imaging=rembo
			db_set linuxmuster-base/imaging $imaging || true
		fi
		echo "imaging=$imaging" >> $NETWORKSETTINGS
	fi

	# patch path to wimport_data in dist.conf (1.1-8)
	if [ -n "$imaging" ]; then
		case "$imaging" in
			linbo|tivoli)
				sed -e "s/^WIMPORTDATA=.*/WIMPORTDATA=\"\/etc\/linuxmuster\/workstations\"/" -i /usr/share/linuxmuster/config/dist.conf
				if [[ -L "$SYSCONFDIR/workstations" && -f "$REMBOFILES/files/global/wimport_data" ]]; then
					rm $SYSCONFDIR/workstations
					cp $REMBOFILES/files/global/wimport_data $SYSCONFDIR/workstations
				fi
				;;
			*)
				sed -e "s/^WIMPORTDATA=.*/WIMPORTDATA=\"\$REMBOFILES\/files\/global\/wimport_data\"/" -i /usr/share/linuxmuster/config/dist.conf
				;;
		esac
	fi

	# remove obsolete unmount_shm from backup.conf (1.2-17)
	if grep -q ^unmount_shm /etc/linuxmuster/backup.conf; then
		echo "Removing obsolete parameter unmount_shm from backup.conf ..."
		cp /etc/linuxmuster/backup.conf /etc/linuxmuster/backup.conf.dpkg-old
		sed -e 's/^unmount_shm.*/# obsolete with linuxmuster-base 1.2-17/' -i /etc/linuxmuster/backup.conf
	fi

	# change obsolete cyrus21 to cyrus2.2 in services parameter in backup.conf (1.2-25)
	if grep -w cyrus21 /etc/linuxmuster/backup.conf | grep -qv ^#; then
		echo "Changing service cyrus21 to cyrus2.2 in backup.conf ..."
		cp /etc/linuxmuster/backup.conf /etc/linuxmuster/backup.conf.dpkg-old
		sed -e 's/cyrus21/cyrus2.2/' -i /etc/linuxmuster/backup.conf
	fi

	# custom login/logout scripts (1.2-6)
	for i in in out; do
		if [ ! -e "$NETLOGONDIR/custom-log$i.sh" ]; then
			echo "Copying $NETLOGONDIR/custom-log$i.sh ..."
			cp $STATICTPLDIR$NETLOGONDIR/custom-log$i.sh $NETLOGONDIR
		fi
	done
	# reparing permissions in netlogondir (1.2-15)
	chown $ADMINISTRATOR:$DOMADMINS $NETLOGONDIR/*
	chmod 664 $NETLOGONDIR/*

	# removing obsolete samba-userlog lockfile (1.2-10)
	if [ -e "${USERLOG}.lock" ]; then
		echo "Removing obsolete lockfile ${USERLOG}.lock ..."
		rm -f ${USERLOG}.lock
	fi

	# linking registry-patches to administrator's home (1.2-15)
	if [ ! -e "$ADMINSHOME/$ADMINISTRATOR/registry-patches" ]; then
		echo "Linking registry-patches to administrator's home ..."
		ln -sf /usr/share/linuxmuster/registry-patches $ADMINSHOME/$ADMINISTRATOR/registry-patches
	fi

	# linbo related update stuff
	if [ "$imaging" = "linbo" ]; then
		# updating rsyncd.conf according to linbo revision 119 (1.2-13)
		if ! grep -q pre-xfer /etc/rsyncd.conf; then
			echo "Updating rsync configuration ..."
			cp $STATICTPLDIR/etc/rsyncd.conf /etc
			/etc/init.d/rsync restart
		fi
		# updating/reparing dhcp configuration according to etch dhcp3-server (1.4-3)
		grep -q ^next-server /etc/dhcp3/dhcpd.conf || dhcp_update=yes
		grep -q ^filename /etc/dhcp3/dhcpd.conf || dhcp_update=yes
		grep -q "server-identifier $servername;" /etc/dhcp3/dhcpd.conf || dhcp_update=yes
		grep -q "server-name \"$servername.$domainname\";" /etc/dhcp3/dhcpd.conf || dhcp_update=yes
		if [ -n "$dhcp_update" ]; then
			echo "Updating dhcp-server configuration ..."
			backup_file /etc/dhcp3/dhcpd.conf
			sed -e "s/@@servername@@/${servername}/g
				s/@@domainname@@/${domainname}/g
				s/@@serverip@@/${serverip}/g
				s/@@ipcopip@@/${ipcopip}/g
				s/@@broadcast@@/${broadcast}/g
				s/@@internalnet@@/${internalnet}/g
				s/@@internsub@@/${internsub}/g
				s/@@internmask@@/${internmask}/g" $DYNTPLDIR/03_dhcp3-server/dhcpd.conf.linbo > /etc/dhcp3/dhcpd.conf
			/etc/init.d/dhcp3-server force-reload
		fi
		# linbo administrative user
		if ! check_id linbo; then
			linbopasswd=`grep ^linbo /etc/rsyncd.secrets | awk -F\: '{ print $2 }'`
			if [ -n "$linbopasswd" ]; then
				echo "Creating linbo user ..."
				sophomorix-useradd --administrator linbo --unix-group $ADMINGROUP --shell /bin/false --gecos "LINBO Administrator" &> /dev/null || true
				sophomorix-passwd --user linbo --pass $linbopasswd &> /dev/null || true
				smbldap-usermod -H '[UX         ]' linbo || true
			fi
		fi
		
	fi

	# reparing nagios2 apache2.conf
	if ! grep -q "$basedn" /etc/nagios2/apache2.conf; then
	sed -e "s/@@serverip@@/$serverip/
		s/@@basedn@@/$basedn/" $DYNTPLDIR/22_nagios/apache2.conf > /etc/nagios2/apache2.conf
		cp /etc/nagios2/apache2.conf /var/lib/linuxmuster-nagios/config/nagios2
		ln -sf /etc/nagios2/apache2.conf /etc/apache2/conf.d/nagios2.conf
	fi
	if grep -q "PaedML 3.0" $SYSCONFDIR/nagios.conf; then
		backup_file /etc/linuxmuster/nagios.conf
		sed -e 's/PaedML 3.0/paedML 4.0.0/g' -i /etc/linuxmuster/nagios.conf
		backup_file /etc/nagios2/conf.d/linuxmuster_main.cfg
		sed -e 's/PaedML 3.0/paedML 4.0.0/g' -i /etc/nagios2/conf.d/linuxmuster_main.cfg
		/etc/init.d/nagios2 restart
	fi

	# creating pam_ldap.secret link
	[ -e /etc/pam_ldap.secret ] || ln -sf ldap.secret /etc/pam_ldap.secret

	# repairing openntpd
	if ! grep -q ^"listen on $serverip" /etc/openntpd/ntpd.conf; then
		cp /etc/openntpd/ntpd.conf /etc/openntpd/ntpd.conf.dpkg-old
		sed -e "s/@@serverip@@/$serverip/" $DYNTPLDIR/99_start-services/ntpd.conf > /etc/openntpd/ntpd.conf
		/etc/init.d/openntpd restart
	fi

	# repairing webmin
	if [ ! -d /var/log/webmin ]; then
		mkdir -p /var/log/webmin
		/etc/init.d/webmin restart
	fi

	# repairing moodle
	if [ -e /etc/moodle/config.php ]; then
		if ! grep -q "\$CFG->wwwroot = '/moodle';" /etc/moodle/config.php; then
			cp /etc/moodle/config.php /etc/moodle/config.php.dpkg-old
			sed -e "s/\$CFG->wwwroot =.*/\$CFG->wwwroot = \'\/moodle\';/g" -i /etc/moodle/config.php
		fi
	fi
	if [ -d /usr/share/moodle ]; then
		[ -L /usr/share/moodle/moodle ] || ln -s . /usr/share/moodle/moodle
	fi

	# ssl-cert permissions
	chgrp ssl-cert /etc/ssl/private -R

	# adding tls support to slapd.conf
	slapdtpl=/usr/share/sophomorix/config-templates/ldap/slapd-standalone.conf.template
	if ! grep -q ^TLS $slapdtpl; then
		cp $slapdtpl $slapdtpl.dpkg-old
		cp $STATICTPLDIR$slapdtpl $slapdtpl
	fi
	[ -e /etc/ldap/slapd.conf.custom ] || cp $STATICTPLDIR/etc/ldap/slapd.conf.custom /etc/ldap
	if ! grep -q ^TLS /etc/ldap/slapd.conf; then
		echo "Adding TLS support to openldap ..."
		cp /etc/ldap/slapd.conf /etc/ldap/slapd.conf.dpkg-old
		cp /etc/default/slapd /etc/default/slapd.dpkg-old
		rootpw=`grep ^rootpw /etc/ldap/slapd.conf | awk '{ print $2 }'`
		sed -e "s/@@message1@@/${message1}/
			s/@@message2@@/${message2}/
			s/@@message3@@/${message3}/
			s/@@basedn@@/${basedn}/g
			s/@@ldappassword@@/${rootpw}/g" $slapdtpl > /etc/ldap/slapd.conf
		sed -e "s/^SLAPD_SERVICES=.*/SLAPD_SERVICES=\"ldap:\/\/\/ ldaps:\/\/\/\"/" -i /etc/default/slapd
		addgroup openldap ssl-cert
		/etc/init.d/slapd restart
	fi

        # reload apache
	apache2ctl graceful || true
	
	# important message if upgrade is necessary
        if [ -n "$upgrade" ]; then
          echo "IMPORTANT!"
          echo "Be sure to make apt-get update and apt-get dist-upgrade very soon!"
        fi

      fi

      ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

db_stop

exit 0

