#!/bin/sh -e
# preinst script for linuxmuster-base
#
# thomas@linuxmuster.net
# 17.01.2013
# GPL v3
#

case "$1" in

upgrade)
		# save workstations data file
		[ -f /etc/linuxmuster/workstations ] && cp /etc/linuxmuster/workstations /etc/linuxmuster/workstations.dpkg-bak
		;;

	*)

		;;

esac

#DEBHELPER#

exit 0
