<?
 # This file has been generated by debconf
 # You can find a commented config file in /usr/share/doc/moodle/

 unset($CFG);

 $CFG->dbtype = 'postgres7';
 $CFG->dbhost = 'localhost';
 $CFG->dbname = 'moodle';
 $CFG->dbuser = 'moodle';
 $CFG->dbpass = '';
 $CFG->prefix = 'mdl_';

 $CFG->dbpersist = "false";

 $CFG->wwwroot = '/moodle';
 $CFG->dirroot = '/usr/share/moodle';
 $CFG->dataroot = '/var/lib/moodle';
 $CFG->directorypermissions = 0750;
 $CFG->admin = 'admin';

 $CFG->respectsessionsettings = true;

$CFG->usecaptcha = true;  // using captcha for registration form

require_once("$CFG->dirroot/lib/setup.php");
// MAKE SURE WHEN YOU EDIT THIS FILE THAT THERE ARE NO SPACES, BLANK LINES,
// RETURNS, OR ANYTHING ELSE AFTER THE TWO CHARACTERS ON THE NEXT LINE.
?>
