<?
 # This file has been generated by debconf
 # You can find a commented config file in /usr/share/doc/moodle/

 unset($CFG);

 $CFG->dbtype = 'postgres7';
 $CFG->dbhost = 'localhost';
 $CFG->dbname = 'moodle';
 $CFG->dbuser = 'moodle';
 $CFG->dbpass = '';
 $CFG->prefix = 'mdl_';

 $CFG->dbpersist = "false";

 $CFG->wwwroot = '';
 $CFG->dirroot = '/usr/share/moodle';
 $CFG->dataroot = '/var/lib/moodle';
 $CFG->directorypermissions = 0750;
 $CFG->admin = 'admin';

 $CFG->respectsessionsettings = true;

if (file_exists("$CFG->dirroot/lib/setup.php"))  {       // Do not edit
	include_once("$CFG->dirroot/lib/setup.php");
} else {
	if ($CFG->dirroot == dirname(__FILE__)) {
		echo "<p>Could not find this file: $CFG->dirroot/lib/setup.php</p>";
		echo "<p>Are you sure all your files have been uploaded?</p>";
	} else {
		echo "<p>Error detected in config.php</p>";
		echo "<p>Error in: \$CFG->dirroot = '$CFG->dirroot';</p>";
		echo "<p>Try this: \$CFG->dirroot = '".dirname(__FILE__)."';</p>";
	}
	die;
}
?>
