#!/bin/sh
#
# $Id: 06linuxmuster 1199 2011-12-17 19:07:20Z tschmitt $

# copy cdrom content to hd 
mkdir -p /target/var/cache/apt/archives
mkdir -p /target/var/cache/linuxmuster
find /cdrom/pool -name \*.deb -exec cp '{}' /target/var/cache/apt/archives \;
cp /cdrom/paedml-release.asc /target/var/cache/linuxmuster
rm /usr/lib/finish-install.d/60cleanup

