#!/bin/sh

# copy cdrom content to hd 
mkdir -p /target/var/cache/apt/archives
mkdir -p /target/var/cache/linuxmuster
find /cdrom/pool -name \*.deb -exec cp '{}' /target/var/cache/apt/archives \;
cp /cdrom/paedml-release.asc /target/var/cache/linuxmuster

