#!/bin/sh
# tweaking stage 2 of installation

timezone=`debconf-get tzconfig/choose_country_zone_multiple`

if [ -n "$timezone" ]; then

  echo "$timezone" > /target/etc/localtime

fi

preseed=`debconf-get preseed/file | cut -d "/" -f6`

if [ "$preseed" = "auto" -o "$preseed" = "expert" ]; then

  chroot /target /usr/share/linuxmuster/scripts/patch_fstab.pl
  cp /target/etc/inittab /target/etc/inittab.real
  cp /usr/share/linuxmuster/inittab.install /target/etc/inittab

fi
